// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';

var $$Array = require("bs-platform/lib/js/array.js");
var React = require("react");

function toString(prim) {
  return prim;
}

function Offers(Props) {
  var offers = Props.offers;
  return React.createElement("ul", undefined, $$Array.map((function (offer) {
                    return React.createElement("li", {
                                key: offer.id.toString()
                              }, offer.reseller, React.createElement("span", undefined, " - $ ", offer.price));
                  }), offers));
}

var make = Offers;

exports.toString = toString;
exports.make = make;
/* react Not a pure module */
