// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';


function toString(prim) {
  return prim;
}

var Utils = /* module */[/* toString */toString];

exports.Utils = Utils;
/* No side effect */
