// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var Products$ReactApolloDemo = require("./components/Products.bs.js");

function App(Props) {
  return React.createElement("div", undefined, React.createElement("h1", undefined, "ReasonReact + GraphQL Demo"), React.createElement(Products$ReactApolloDemo.make, { }));
}

var make = App;

exports.make = make;
/* react Not a pure module */
