// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var ReactDOMRe = require("reason-react/src/ReactDOMRe.js");
var ReactApollo = require("react-apollo");
var App$ReactApolloDemo = require("./App.bs.js");
var Client$ReactApolloDemo = require("./Client.bs.js");

ReactDOMRe.renderToElementWithId(React.createElement(ReactApollo.ApolloProvider, {
          client: Client$ReactApolloDemo.instance,
          children: React.createElement(App$ReactApolloDemo.make, { })
        }), "index");

/*  Not a pure module */
